import json
import re

# RoomType mapping
ROOM_TYPE_MAP = [
    (3, ["chem", "chemical", "hydraulic", "geotechnical", "materials"]),
    (4, ["automotive", "auto shop"]),
    (5, ["machinery", "mechanical shop", "mechanical"]),
    (6, ["robotics", "robotics lab"]),
    (2, ["lab", "laboratory", "shop"]),
    (1, ["room", "faculty", "center", "office", "gym", "school", "resource", "temporary", "tba", "not set", "claver", "sb", "gs", "rm", "cot", "eb", "et", "nr", "ol", "mrc", "hrm", "ecl", "cel", "comlab", "ias", "ftsr", "elexsr", "dsr", "asr", "g1", "g2"]),
]

def get_room_type(room_name):
    name = room_name.lower()
    for type_id, keywords in ROOM_TYPE_MAP:
        if any(kw in name for kw in keywords):
            return type_id
    return 1  # Default to lecture room

def get_floor(room_code):
    # Try to extract floor from room code like 'EB 201' -> 2
    match = re.search(r"\\b(\d{3,})\\b", room_code)
    if match:
        return int(str(match.group(1))[0])
    # Try to extract from codes like 'CL 4' -> 4
    match = re.search(r"\\b(\d)\\b", room_code)
    if match:
        return int(match.group(1))
    return 1  # Default to 1 if not found

room_list = [
    {"RoomID" : 0, "RoomCode" : "NS", "RoomName" : "Not Set"},
    {"RoomID" : 8, "RoomCode" : "EB 201", "RoomName" : "CEIT Faculty Room"},
    {"RoomID" : 9, "RoomCode" : "EB 202", "RoomName" : "Electronics Engineering Lab"},
    {"RoomID" : 10, "RoomCode" : "EB 203", "RoomName" : "Electrical Engineering Lab"},
    {"RoomID" : 11, "RoomCode" : "EB 204", "RoomName" : "Computer Engineering Lab 1"},
    {"RoomID" : 12, "RoomCode" : "EB 205", "RoomName" : "Computer Engineering Lab 2"},
    {"RoomID" : 13, "RoomCode" : "EB 206", "RoomName" : "ITE Laboratory 1"},
    {"RoomID" : 14, "RoomCode" : "EB 207", "RoomName" : "ITE Laboratory 2"},
    {"RoomID" : 15, "RoomCode" : "EB 208", "RoomName" : "ITE Laboratory 3"},
    {"RoomID" : 16, "RoomCode" : "EB 209", "RoomName" : "ITE Laboratory 4"},
    {"RoomID" : 17, "RoomCode" : "EB 210", "RoomName" : "ITE Laboratory 5"},
    {"RoomID" : 18, "RoomCode" : "EB 301", "RoomName" : "CEIT Room 301"},
    {"RoomID" : 19, "RoomCode" : "EB 302", "RoomName" : "CEIT Room 302"},
    {"RoomID" : 20, "RoomCode" : "EB 303", "RoomName" : "CEIT Room 303"},
    {"RoomID" : 21, "RoomCode" : "EB 304", "RoomName" : "CEIT Room 304"},
    {"RoomID" : 22, "RoomCode" : "EB 305", "RoomName" : "CEIT Room 305"},
    {"RoomID" : 23, "RoomCode" : "EB 306", "RoomName" : "CEIT Room 306"},
    {"RoomID" : 24, "RoomCode" : "EB 307", "RoomName" : "CEIT Room 307"},
    {"RoomID" : 25, "RoomCode" : "EB 308", "RoomName" : "CEIT Room 308"},
    {"RoomID" : 26, "RoomCode" : "EB 309", "RoomName" : "CEIT Room 309"},
    {"RoomID" : 27, "RoomCode" : "EB 310", "RoomName" : "CEIT Room 310"},
    {"RoomID" : 28, "RoomCode" : "EB 311", "RoomName" : "CEIT Room 311"},
    {"RoomID" : 30, "RoomCode" : "Jeep Lab", "RoomName" : "Jeep Laboratory"},
    {"RoomID" : 31, "RoomCode" : "CL 1", "RoomName" : "CEIT Computer Laboratory 1"},
    {"RoomID" : 32, "RoomCode" : "CL 2", "RoomName" : "CEIT Computer Laboratory 2"},
    {"RoomID" : 33, "RoomCode" : "CL 3", "RoomName" : "CEIT Computer Laboratory 3"},
    {"RoomID" : 34, "RoomCode" : "CL 4", "RoomName" : "CEIT Computer Laboratory 4"},
    {"RoomID" : 35, "RoomCode" : "CL 5", "RoomName" : "CEIT Computer Laboratory 5"},
    {"RoomID" : 36, "RoomCode" : "MRC", "RoomName" : "Multimedia Resouce Center"},
    {"RoomID" : 37, "RoomCode" : "COT 251", "RoomName" : "COT Room 251"},
    {"RoomID" : 38, "RoomCode" : "COT 252", "RoomName" : "COT Room 252"},
    {"RoomID" : 39, "RoomCode" : "COT 253", "RoomName" : "COT Room 253"},
    {"RoomID" : 40, "RoomCode" : "COT 254", "RoomName" : "COT Room 254"},
    {"RoomID" : 41, "RoomCode" : "COT 255", "RoomName" : "COT Room 255"},
    {"RoomID" : 42, "RoomCode" : "COT 256", "RoomName" : "COT Room 256"},
    {"RoomID" : 43, "RoomCode" : "Room 1", "RoomName" : "Temporary Room 1"},
    {"RoomID" : 44, "RoomCode" : "Room 2", "RoomName" : "Temporary Room 2"},
    {"RoomID" : 45, "RoomCode" : "Room 3", "RoomName" : "Temporary Room 3"},
    {"RoomID" : 46, "RoomCode" : "COT 268", "RoomName" : "COT Room 268"},
    {"RoomID" : 47, "RoomCode" : "JAL", "RoomName" : "Jeep Accelerated Laboratory"},
    {"RoomID" : 48, "RoomCode" : "CEL2", "RoomName" : "Civil Engineering Laboratory 2"},
    {"RoomID" : 49, "RoomCode" : "OL 1", "RoomName" : "Old Library 1"},
    {"RoomID" : 50, "RoomCode" : "OL 2", "RoomName" : "Old Library 2"},
    {"RoomID" : 51, "RoomCode" : "OL 3", "RoomName" : "Old Library 3"},
    {"RoomID" : 52, "RoomCode" : "Ground", "RoomName" : "Ground"},
    {"RoomID" : 53, "RoomCode" : "COT 266", "RoomName" : "COT Room 266"},
    {"RoomID" : 54, "RoomCode" : "COT 267", "RoomName" : "COT Room 267"},
    {"RoomID" : 55, "RoomCode" : "COT 269", "RoomName" : "COT Room 269"},
    {"RoomID" : 56, "RoomCode" : "MRC 1", "RoomName" : "Multimedia Resource Center 1"},
    {"RoomID" : 57, "RoomCode" : "MRC 2", "RoomName" : "Multimedia Resource Center 2"},
    {"RoomID" : 58, "RoomCode" : "EB 312", "RoomName" : "CEIT Room 312"},
    {"RoomID" : 59, "RoomCode" : "EB 211", "RoomName" : "CEIT Room 211"},
    {"RoomID" : 60, "RoomCode" : "SR", "RoomName" : "Sample Room"},
    {"RoomID" : 61, "RoomCode" : "COT 272", "RoomName" : "COT Room 272"},
    {"RoomID" : 62, "RoomCode" : "COT 367", "RoomName" : "COT Room 367"},
    {"RoomID" : 63, "RoomCode" : "COT 357", "RoomName" : "COT Room 357"},
    {"RoomID" : 64, "RoomCode" : "NR 1", "RoomName" : "New Room 1"},
    {"RoomID" : 65, "RoomCode" : "NR 2", "RoomName" : "New Room 2"},
    {"RoomID" : 66, "RoomCode" : "NR 3", "RoomName" : "New Room 3"},
    {"RoomID" : 67, "RoomCode" : "COT 366", "RoomName" : "COT Room 366"},
    {"RoomID" : 68, "RoomCode" : "ET 276", "RoomName" : "COT Room 276"},
    {"RoomID" : 69, "RoomCode" : "COT 250", "RoomName" : "COT Room 250"},
    {"RoomID" : 70, "RoomCode" : "COT 364", "RoomName" : "COT Room 364"},
    {"RoomID" : 71, "RoomCode" : "COT 247", "RoomName" : "COT Room 247"},
    {"RoomID" : 72, "RoomCode" : "COT 368", "RoomName" : "COT Room 368"},
    {"RoomID" : 73, "RoomCode" : "ELEXLAB1", "RoomName" : "Electronics Laboratory 1"},
    {"RoomID" : 74, "RoomCode" : "ELEXLAB2", "RoomName" : "Electronics Laboratory 2"},
    {"RoomID" : 75, "RoomCode" : "COT 356", "RoomName" : "COT Room 356"},
    {"RoomID" : 76, "RoomCode" : "COT 360", "RoomName" : "COT Room 360"},
    {"RoomID" : 77, "RoomCode" : "ELECLAB1", "RoomName" : "Electricity Laboratory 1"},
    {"RoomID" : 78, "RoomCode" : "ELECLAB2", "RoomName" : "Electricity Laboratory 2"},
    {"RoomID" : 79, "RoomCode" : "COT 245", "RoomName" : "COT Room 245"},
    {"RoomID" : 80, "RoomCode" : "COT 246", "RoomName" : "COT Room 246"},
    {"RoomID" : 81, "RoomCode" : "COT 248", "RoomName" : "COT Room 248"},
    {"RoomID" : 82, "RoomCode" : "COT 249", "RoomName" : "COT Room 249"},
    {"RoomID" : 83, "RoomCode" : "COT 354", "RoomName" : "COT Room 354"},
    {"RoomID" : 84, "RoomCode" : "COT 352", "RoomName" : "COT Room 352"},
    {"RoomID" : 85, "RoomCode" : "COT 351", "RoomName" : "COT Room 351"},
    {"RoomID" : 86, "RoomCode" : "COT 353", "RoomName" : "COT Room 353"},
    {"RoomID" : 87, "RoomCode" : "COT 358", "RoomName" : "COT Room 358"},
    {"RoomID" : 88, "RoomCode" : "COT 361", "RoomName" : "COT Room 361"},
    {"RoomID" : 89, "RoomCode" : "COT 362", "RoomName" : "COT Room 362"},
    {"RoomID" : 90, "RoomCode" : "COT 363", "RoomName" : "COT Room 363"},
    {"RoomID" : 91, "RoomCode" : "COT 365", "RoomName" : "COT Room 365"},
    {"RoomID" : 92, "RoomCode" : "COT 369", "RoomName" : "COT Room 369"},
    {"RoomID" : 93, "RoomCode" : "COT 258", "RoomName" : "COT Room 258"},
    {"RoomID" : 94, "RoomCode" : "COT 257", "RoomName" : "COT Room 257"},
    {"RoomID" : 95, "RoomCode" : "COT 259", "RoomName" : "COT Room 259"},
    {"RoomID" : 96, "RoomCode" : "COT 260", "RoomName" : "COT Room 260"},
    {"RoomID" : 97, "RoomCode" : "COT 261", "RoomName" : "COT Room 261"},
    {"RoomID" : 98, "RoomCode" : "COT 262", "RoomName" : "COT Room 262"},
    {"RoomID" : 99, "RoomCode" : "COT 263", "RoomName" : "COT Room 263"},
    {"RoomID" : 100, "RoomCode" : "COT 264", "RoomName" : "COT Room 264"},
    {"RoomID" : 101, "RoomCode" : "COT 265", "RoomName" : "COT Room 265"},
    {"RoomID" : 102, "RoomCode" : "COT 270", "RoomName" : "COT Room 270"},
    {"RoomID" : 103, "RoomCode" : "COT 271", "RoomName" : "COT Room 271"},
    {"RoomID" : 104, "RoomCode" : "COT 273", "RoomName" : "COT Room 273"},
    {"RoomID" : 105, "RoomCode" : "COT 274", "RoomName" : "COT Room 274"},
    {"RoomID" : 106, "RoomCode" : "ET 275", "RoomName" : "COT Room 275"},
    {"RoomID" : 107, "RoomCode" : "ET 277", "RoomName" : "COT Room 277"},
    {"RoomID" : 108, "RoomCode" : "ET 278", "RoomName" : "COT Room 278"},
    {"RoomID" : 109, "RoomCode" : "ET 279", "RoomName" : "COT Room 279"},
    {"RoomID" : 110, "RoomCode" : "ET 280", "RoomName" : "COT Room 280"},
    {"RoomID" : 111, "RoomCode" : "COT 359", "RoomName" : "COT Room 359"},
    {"RoomID" : 112, "RoomCode" : "NR 4", "RoomName" : "New Room 4"},
    {"RoomID" : 113, "RoomCode" : "NR 5", "RoomName" : "New Room 5"},
    {"RoomID" : 114, "RoomCode" : "ET 158a", "RoomName" : "COT Room 158a"},
    {"RoomID" : 115, "RoomCode" : "ECL 1", "RoomName" : "Engineering Computer Laboratory 1"},
    {"RoomID" : 116, "RoomCode" : "ECL 2", "RoomName" : "Engineering Computer Laboratory 2"},
    {"RoomID" : 117, "RoomCode" : "CEL 1", "RoomName" : "Civil Engineering Laboratory 1"},
    {"RoomID" : 118, "RoomCode" : "CEL 1", "RoomName" : "Civil Engineering Laboratory 1"},
    {"RoomID" : 119, "RoomCode" : "NR", "RoomName" : "New Room"},
    {"RoomID" : 120, "RoomCode" : "TBA", "RoomName" : "TBA"},
    {"RoomID" : 121, "RoomCode" : "ET 159", "RoomName" : "COT Room 159"},
    {"RoomID" : 122, "RoomCode" : "GS 1", "RoomName" : "Graduate School 1"},
    {"RoomID" : 123, "RoomCode" : "GS 2", "RoomName" : "Graduate School 2"},
    {"RoomID" : 124, "RoomCode" : "RM A", "RoomName" : "Temporary Room A"},
    {"RoomID" : 125, "RoomCode" : "RM B", "RoomName" : "Temporary Room B"},
    {"RoomID" : 126, "RoomCode" : "RM C", "RoomName" : "Temporary Room C"},
    {"RoomID" : 127, "RoomCode" : "RM D", "RoomName" : "Temporary Room D"},
    {"RoomID" : 128, "RoomCode" : "ET 235", "RoomName" : "COT Room 235"},
    {"RoomID" : 129, "RoomCode" : "SB 01", "RoomName" : "SB 01"},
    {"RoomID" : 130, "RoomCode" : "SB 02", "RoomName" : "SB 02"},
    {"RoomID" : 131, "RoomCode" : "SB 03", "RoomName" : "SB 03"},
    {"RoomID" : 132, "RoomCode" : "EB 401", "RoomName" : "CEIT Room 401"},
    {"RoomID" : 133, "RoomCode" : "EB 402", "RoomName" : "CEIT Room 402"},
    {"RoomID" : 134, "RoomCode" : "EB 403", "RoomName" : "CEIT Room 403"},
    {"RoomID" : 135, "RoomCode" : "EB 404", "RoomName" : "CEIT Room 404"},
    {"RoomID" : 136, "RoomCode" : "EB 405", "RoomName" : "CEIT Room 405"},
    {"RoomID" : 137, "RoomCode" : "EB 406", "RoomName" : "CEIT Room 406"},
    {"RoomID" : 138, "RoomCode" : "EB 407", "RoomName" : "CEIT Room 407"},
    {"RoomID" : 139, "RoomCode" : "EB 408", "RoomName" : "CEIT Room 408"},
    {"RoomID" : 140, "RoomCode" : "EB 409", "RoomName" : "CEIT Room 409"},
    {"RoomID" : 141, "RoomCode" : "EB 410", "RoomName" : "CEIT Room 410"},
    {"RoomID" : 142, "RoomCode" : "EB 411", "RoomName" : "CEIT Room 411"},
    {"RoomID" : 143, "RoomCode" : "EB 412", "RoomName" : "CEIT Room 412"},
    {"RoomID" : 144, "RoomCode" : "Gym", "RoomName" : "Gymnassium"},
    {"RoomID" : 145, "RoomCode" : "CTE 226", "RoomName" : "CTE Room 226"},
    {"RoomID" : 146, "RoomCode" : "CTE 227", "RoomName" : "CTE Room 227"},
    {"RoomID" : 147, "RoomCode" : "CTE 228", "RoomName" : "CTE Room 228"},
    {"RoomID" : 148, "RoomCode" : "CTE 229", "RoomName" : "CTE Room 229"},
    {"RoomID" : 149, "RoomCode" : "CTE 230", "RoomName" : "CTE Room 230"},
    {"RoomID" : 150, "RoomCode" : "CTE 231", "RoomName" : "CTE Room 231"},
    {"RoomID" : 151, "RoomCode" : "CTE 232", "RoomName" : "CTE Room 232"},
    {"RoomID" : 152, "RoomCode" : "CTE 233", "RoomName" : "CTE Room 233"},
    {"RoomID" : 153, "RoomCode" : "CTE 234", "RoomName" : "CTE Room 234"},
    {"RoomID" : 154, "RoomCode" : "CTE 235", "RoomName" : "CTE Room 235"},
    {"RoomID" : 155, "RoomCode" : "CTE 236", "RoomName" : "CTE Room 236"},
    {"RoomID" : 156, "RoomCode" : "CTE 237", "RoomName" : "CTE Room 237"},
    {"RoomID" : 157, "RoomCode" : "CTE 240", "RoomName" : "CTE Room 240"},
    {"RoomID" : 158, "RoomCode" : "CTE 299", "RoomName" : "CTE Room 299"},
    {"RoomID" : 159, "RoomCode" : "CTE 216", "RoomName" : "CTE Room 216"},
    {"RoomID" : 160, "RoomCode" : "UG", "RoomName" : "Under the Gymnassium"},
    {"RoomID" : 161, "RoomCode" : "COT 355", "RoomName" : "COT Room 355"},
    {"RoomID" : 162, "RoomCode" : "SWK", "RoomName" : "SWK"},
    {"RoomID" : 165, "RoomCode" : "ET 375", "RoomName" : "COT Room 375"},
    {"RoomID" : 166, "RoomCode" : "ET 151", "RoomName" : "COT Room 151"},
    {"RoomID" : 167, "RoomCode" : "COT 244", "RoomName" : "COT Room 244"},
    {"RoomID" : 168, "RoomCode" : "COT 144", "RoomName" : "COT Room 144"},
    {"RoomID" : 169, "RoomCode" : "COT 148", "RoomName" : "COT Room 148"},
    {"RoomID" : 170, "RoomCode" : "COT 147", "RoomName" : "Automotive Lab"},
    {"RoomID" : 171, "RoomCode" : "COT 145", "RoomName" : "COT Room 145"},
    {"RoomID" : 172, "RoomCode" : "COT 146", "RoomName" : "COT Room 146"},
    {"RoomID" : 173, "RoomCode" : "ET 152", "RoomName" : "COT Room 152"},
    {"RoomID" : 174, "RoomCode" : "ET 153", "RoomName" : "COT Room 153"},
    {"RoomID" : 175, "RoomCode" : "ET 154", "RoomName" : "COT Room 154"},
    {"RoomID" : 176, "RoomCode" : "ET 155", "RoomName" : "COT Room 155"},
    {"RoomID" : 177, "RoomCode" : "ET 156", "RoomName" : "COT Room 156"},
    {"RoomID" : 178, "RoomCode" : "ET 157", "RoomName" : "COT Room 157"},
    {"RoomID" : 179, "RoomCode" : "ACCRE", "RoomName" : "Accreditation Center"},
    {"RoomID" : 180, "RoomCode" : "COT 150", "RoomName" : "COT Room 150"},
    {"RoomID" : 181, "RoomCode" : "COT 202", "RoomName" : "COT Room 202"},
    {"RoomID" : 182, "RoomCode" : "ET-203", "RoomName" : "COT Room 203"},
    {"RoomID" : 183, "RoomCode" : "ComLab", "RoomName" : "Computer Laboratory"},
    {"RoomID" : 184, "RoomCode" : "IAS", "RoomName" : "Industrial Arts Shop"},
    {"RoomID" : 185, "RoomCode" : "FTSR", "RoomName" : "Food Technical Shop Room"},
    {"RoomID" : 186, "RoomCode" : "ELESR", "RoomName" : "Electrical Shop Room"},
    {"RoomID" : 187, "RoomCode" : "ELEXSR", "RoomName" : "Electronics Shop Room"},
    {"RoomID" : 188, "RoomCode" : "DSR", "RoomName" : "Drafting Shop Room"},
    {"RoomID" : 189, "RoomCode" : "ASR", "RoomName" : "Auto Shop Room"},
    {"RoomID" : 190, "RoomCode" : "HRM RM 1", "RoomName" : "HRM ROOM 1"},
    {"RoomID" : 191, "RoomCode" : "HRM RM 2", "RoomName" : "HRM ROOM 2"},
    {"RoomID" : 192, "RoomCode" : "HRM LAB 1", "RoomName" : "HRM LABORATORY 1"},
    {"RoomID" : 193, "RoomCode" : "HRM LAB 2", "RoomName" : "HRM LABORATORY 2"},
    {"RoomID" : 194, "RoomCode" : "HRM RM 3", "RoomName" : "HRM ROOM 3"},
    {"RoomID" : 195, "RoomCode" : "HRM RM 4", "RoomName" : "HRM ROOM 4"},
    {"RoomID" : 196, "RoomCode" : "HRM LAB 3", "RoomName" : "HRM LABORATORY 3"},
    {"RoomID" : 197, "RoomCode" : "HRM LAB 4 ", "RoomName" : "HRM LABORATORY 4 "},
    {"RoomID" : 198, "RoomCode" : "COT 158", "RoomName" : "COT Room 158"},
    {"RoomID" : 199, "RoomCode" : "G1", "RoomName" : "G1"},
    {"RoomID" : 200, "RoomCode" : "ROOM 305", "RoomName" : "TEMPORARY ROOM 305"},
    {"RoomID" : 201, "RoomCode" : "ROOM 304", "RoomName" : "TEMPORARY ROOM 304"},
    {"RoomID" : 202, "RoomCode" : "ROOM 302", "RoomName" : "TEMPORARY ROOM 302"},
    {"RoomID" : 203, "RoomCode" : "NOT SET", "RoomName" : "Room not set"},
    {"RoomID" : 205, "RoomCode" : "RS 228", "RoomName" : "Related subjects room 228"},
    {"RoomID" : 206, "RoomCode" : "RS 229", "RoomName" : "Related subjects room 229"},
    {"RoomID" : 207, "RoomCode" : "RS 231", "RoomName" : "Related subjects room 231"},
    {"RoomID" : 208, "RoomCode" : "RS 232", "RoomName" : "Related subjects room 232"},
    {"RoomID" : 209, "RoomCode" : "RS 233", "RoomName" : "Related subjects room 233"},
    {"RoomID" : 210, "RoomCode" : "RS 234", "RoomName" : "Related subjects room 234"},
    {"RoomID" : 211, "RoomCode" : "RS 235", "RoomName" : "Related subjects room 235"},
    {"RoomID" : 212, "RoomCode" : "RS 236", "RoomName" : "Related subjects room 236"},
    {"RoomID" : 213, "RoomCode" : "RS 237", "RoomName" : "Related subjects room 237"},
    {"RoomID" : 214, "RoomCode" : "HS 01", "RoomName" : "High school room 1"},
    {"RoomID" : 215, "RoomCode" : "HS 02", "RoomName" : "High school room 2"},
    {"RoomID" : 216, "RoomCode" : "HS 03", "RoomName" : "High school room 3"},
    {"RoomID" : 217, "RoomCode" : "HS 04", "RoomName" : "High school room 4"},
    {"RoomID" : 218, "RoomCode" : "HS 05", "RoomName" : "High school room 5"},
    {"RoomID" : 219, "RoomCode" : "G2", "RoomName" : "G2"},
    {"RoomID" : 220, "RoomCode" : "RM 303", "RoomName" : "Claver303"},
    {"RoomID" : 221, "RoomCode" : "RM 302", "RoomName" : "Claver302"},
    {"RoomID" : 222, "RoomCode" : "RM 301", "RoomName" : "Claver301"},
    {"RoomID" : 223, "RoomCode" : "RM 304", "RoomName" : "Claver304"},
    {"RoomID" : 224, "RoomCode" : "RM 305", "RoomName" : "Claver305"},
    {"RoomID" : 225, "RoomCode" : "RM 306", "RoomName" : "Claver306"},
    {"RoomID" : 226, "RoomCode" : "RM 307", "RoomName" : "Claver307"},
    {"RoomID" : 227, "RoomCode" : "RM 308", "RoomName" : "Claver308"},
    {"RoomID" : 228, "RoomCode" : "RM 309", "RoomName" : "Claver309"},
    {"RoomID" : 229, "RoomCode" : "3rd Floor CEIT", "RoomName" : "GS3-1"},
    {"RoomID" : 230, "RoomCode" : "CAS-O", "RoomName" : "CAS Office"},
    {"RoomID" : 231, "RoomCode" : "COT 140", "RoomName" : "Hydraulic Engineering Lab"},
    {"RoomID" : 232, "RoomCode" : "COT 141", "RoomName" : "Geotechnical and Materials Engineering Lab"},
    {"RoomID" : 233, "RoomCode" : "COT 101", "RoomName" : "COT Room 101"},
    {"RoomID" : 234, "RoomCode" : "COT 102", "RoomName" : "COT Room 102"},
    {"RoomID" : 235, "RoomCode" : "COT 161", "RoomName" : "COT Room 161"},
    {"RoomID" : 236, "RoomCode" : "COT 143", "RoomName" : "COT Room 143"},
    {"RoomID" : 237, "RoomCode" : "COT 149", "RoomName" : "COT Room 149"},
    {"RoomID" : 238, "RoomCode" : "COT 137", "RoomName" : "COT Room 137"},
    {"RoomID" : 239, "RoomCode" : "COT 136", "RoomName" : "COT Room 136"},
    {"RoomID" : 240, "RoomCode" : "COT 239", "RoomName" : "COT Room 239"},
    {"RoomID" : 241, "RoomCode" : "COT 238", "RoomName" : "COT Room 238"},
    {"RoomID" : 242, "RoomCode" : "COT 240", "RoomName" : "COT Room 240"},
    {"RoomID" : 243, "RoomCode" : "COT 244-B", "RoomName" : "COT Room 244-B"},
    {"RoomID" : 244, "RoomCode" : "COT 244-A", "RoomName" : "COT Room 244-A"},
    {"RoomID" : 245, "RoomCode" : "COT 243", "RoomName" : "COT Room 243"},
    {"RoomID" : 246, "RoomCode" : "COT 342", "RoomName" : "COT Room 342"},
    {"RoomID" : 247, "RoomCode" : "COT 241", "RoomName" : "COT Room 241"},
    {"RoomID" : 248, "RoomCode" : "COT 362-A", "RoomName" : "COT Room 362-A"},
    {"RoomID" : 249, "RoomCode" : "COT 301", "RoomName" : "COT Room 301"},
    {"RoomID" : 250, "RoomCode" : "COT 302", "RoomName" : "COT Room 302"},
    {"RoomID" : 251, "RoomCode" : "COT 201", "RoomName" : "COT Room 201"},
    {"RoomID" : 252, "RoomCode" : "EB 212", "RoomName" : "EB Room 212"},
    {"RoomID" : 253, "RoomCode" : "EB 213", "RoomName" : "EB Room 213"},
    {"RoomID" : 254, "RoomCode" : "EB 512", "RoomName" : "EB Room 512"},
    {"RoomID" : 255, "RoomCode" : "EB 511", "RoomName" : "EB Room 511"},
    {"RoomID" : 256, "RoomCode" : "EB 510", "RoomName" : "EB Room 510"},
    {"RoomID" : 257, "RoomCode" : "EB 509", "RoomName" : "EB Room 509"},
    {"RoomID" : 258, "RoomCode" : "EB 508", "RoomName" : "EB Room 508"},
    {"RoomID" : 259, "RoomCode" : "EB 507", "RoomName" : "EB Room 507"},
    {"RoomID" : 260, "RoomCode" : "EB 505", "RoomName" : "EB Room 505"},
    {"RoomID" : 261, "RoomCode" : "EB 504", "RoomName" : "EB Room 504"},
    {"RoomID" : 262, "RoomCode" : "EB 503", "RoomName" : "EB Room 503"},
    {"RoomID" : 263, "RoomCode" : "EB 502", "RoomName" : "EB Room 502"},
    {"RoomID" : 264, "RoomCode" : "COM LAB", "RoomName" : "ClaverLab"},
    {"RoomID" : 265, "RoomCode" : "NDRRMC", "RoomName" : "Claver NDRRMC BLBG."},
    {"RoomID" : 266, "RoomCode" : "RM 1", "RoomName" : "Claver1"},
    {"RoomID" : 267, "RoomCode" : "MSR", "RoomName" : "Mechanical Shop Room"},
    {"RoomID" : 268, "RoomCode" : "Rm. 311", "RoomName" : "Claver Extension"},
    {"RoomID" : 269, "RoomCode" : "SB 201", "RoomName" : "SB 201"},
    {"RoomID" : 270, "RoomCode" : "SB 301", "RoomName" : "SB 301"},
    {"RoomID" : 271, "RoomCode" : "SB 302", "RoomName" : "SB 302"},
    {"RoomID" : 272, "RoomCode" : "SB 202", "RoomName" : "SB 202"},
    {"RoomID" : 273, "RoomCode" : "ET 258", "RoomName" : "Room 258"},
    {"RoomID" : 274, "RoomCode" : "ET 262", "RoomName" : "Room 262"},
    {"RoomID" : 275, "RoomCode" : "ET 261", "RoomName" : "Room 261"},
    {"RoomID" : 276, "RoomCode" : "ET 259", "RoomName" : "Room 259"},
    {"RoomID" : 277, "RoomCode" : "ET 260", "RoomName" : "Room 260"},
    {"RoomID" : 278, "RoomCode" : "ET 256", "RoomName" : "Room 256"},
    {"RoomID" : 279, "RoomCode" : "ET 257", "RoomName" : "Room 257"}
]

output = []
for room in room_list:
    room_type = get_room_type(room["RoomName"])
    floor = get_floor(room["RoomCode"])
    output.append({
        "RoomID": room["RoomID"],
        "RoomType": room_type,
        "Floor": floor,
        "RoomName": room["RoomName"]
    })

with open("room.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"room.json generated with {len(output)} rooms.") 